"use client";

import { useRef } from "react";

interface NoteWeakness {
  concept: string;
  errorType: string;
  rootIssue: string;
}

interface NoteData {
  studentId: string;
  displayName: string;
  topWeaknesses: NoteWeakness[];
  improvementTips: string[];
  teacherFollowUp: string;
}

interface SavedNote {
  noteId: string;
  displayName: string;
  note: NoteData;
  generatedAt: number;
  status: string;
  error?: string;
}

const ERROR_TYPE_STYLE: Record<string, { bg: string; color: string }> = {
  conceptual: { bg: "#FDECEA", color: "#A63D2E" },
  procedural: { bg: "#FEF4E5", color: "#A25E1A" },
  careless: { bg: "#E3EDF7", color: "#2B5E9E" },
};

export default function StudentNoteCard({
  note,
  onRegenerate,
  regenerating,
}: {
  note: SavedNote;
  onRegenerate?: () => void;
  regenerating?: boolean;
}) {
  const printRef = useRef<HTMLDivElement>(null);

  if (note.status === "error") {
    return (
      <div className="edu-card" style={{ padding: 20, borderLeft: "3px solid #A63D2E" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div>
            <p style={{ fontSize: 14, fontWeight: 600, color: "#A63D2E", margin: 0 }}>
              Failed to generate note for {note.displayName}
            </p>
            <p className="edu-muted" style={{ fontSize: 12, margin: "4px 0 0" }}>{note.error}</p>
          </div>
          {onRegenerate && (
            <button className="edu-btn-outline" style={{ padding: "4px 12px", fontSize: 12 }} onClick={onRegenerate} disabled={regenerating}>
              {regenerating ? "Generating…" : "Retry"}
            </button>
          )}
        </div>
      </div>
    );
  }

  const data = note.note;
  if (!data) return null;

  function handleCopy() {
    const lines = [
      `Student Note: ${data.displayName}`,
      `Generated: ${new Date(note.generatedAt).toLocaleString()}`,
      "",
      "Top Weaknesses:",
      ...data.topWeaknesses.map((w, i) => `  ${i + 1}. ${w.concept} (${w.errorType}): ${w.rootIssue}`),
      "",
      "Improvement Tips:",
      ...data.improvementTips.map((t, i) => `  ${i + 1}. ${t}`),
      "",
      `Teacher Follow-Up: ${data.teacherFollowUp}`,
      "",
      "— Generated by EduInsight AI (draft)",
    ];
    navigator.clipboard.writeText(lines.join("\n"));
  }

  function handlePrint() {
    if (!printRef.current) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<html><head><title>Note: ${data.displayName}</title><style>body{font-family:system-ui,sans-serif;padding:32px;max-width:700px;margin:0 auto;color:#3D3229}h2{font-size:20px}h3{font-size:15px;margin-top:20px}.badge{display:inline-block;padding:2px 8px;border-radius:3px;font-size:11px;font-weight:600}.tip{padding:6px 0;border-bottom:1px solid #eee}.footer{margin-top:24px;font-size:11px;color:#999}</style></head><body>`);
    win.document.write(printRef.current.innerHTML);
    win.document.write(`</body></html>`);
    win.document.close();
    win.print();
  }

  return (
    <div className="edu-card edu-fade-in" style={{ padding: 20 }}>
      <div ref={printRef}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 14 }}>
          <div>
            <h3 className="edu-heading" style={{ fontSize: 16, margin: 0, textTransform: "capitalize" }}>
              {data.displayName}
            </h3>
            <p className="edu-muted" style={{ fontSize: 11, margin: "2px 0 0" }}>
              Generated {new Date(note.generatedAt).toLocaleString()}
            </p>
          </div>
          <span style={{ fontSize: 10, color: "#8A7D6F", fontStyle: "italic" }}>AI-generated draft</span>
        </div>

        <div style={{ marginBottom: 16 }}>
          <h4 style={{ fontSize: 13, fontWeight: 600, color: "#5A5048", margin: "0 0 8px", textTransform: "uppercase", letterSpacing: 0.5 }}>
            Top Weaknesses
          </h4>
          {data.topWeaknesses.map((w, i) => {
            const style = ERROR_TYPE_STYLE[w.errorType] ?? ERROR_TYPE_STYLE.careless;
            return (
              <div key={i} style={{ padding: "8px 0", borderBottom: i < data.topWeaknesses.length - 1 ? "1px solid #F0ECE5" : "none" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                  <span style={{ fontWeight: 600, fontSize: 13 }}>{w.concept}</span>
                  <span style={{ fontSize: 10, fontWeight: 600, padding: "1px 6px", borderRadius: 3, background: style.bg, color: style.color, textTransform: "uppercase" }}>
                    {w.errorType}
                  </span>
                </div>
                <p style={{ fontSize: 13, color: "#5A5048", margin: 0, lineHeight: 1.5 }}>{w.rootIssue}</p>
              </div>
            );
          })}
        </div>

        <div style={{ marginBottom: 16 }}>
          <h4 style={{ fontSize: 13, fontWeight: 600, color: "#5A5048", margin: "0 0 8px", textTransform: "uppercase", letterSpacing: 0.5 }}>
            Improvement Tips
          </h4>
          <ol style={{ margin: 0, paddingLeft: 20, fontSize: 13, lineHeight: 1.7, color: "#3D3229" }}>
            {data.improvementTips.map((tip, i) => (
              <li key={i} style={{ marginBottom: 4 }}>{tip}</li>
            ))}
          </ol>
        </div>

        <div style={{ background: "#F5F0E9", borderRadius: 6, padding: "12px 16px" }}>
          <h4 style={{ fontSize: 12, fontWeight: 600, color: "#C17A56", margin: "0 0 4px", textTransform: "uppercase", letterSpacing: 0.5 }}>
            Teacher Follow-Up
          </h4>
          <p style={{ fontSize: 13, color: "#3D3229", margin: 0, lineHeight: 1.5 }}>{data.teacherFollowUp}</p>
        </div>

        <p style={{ fontSize: 10, color: "#B5AA9C", marginTop: 12, fontStyle: "italic" }}>
          — Generated by EduInsight AI (draft)
        </p>
      </div>

      <div style={{ display: "flex", gap: 8, marginTop: 14, borderTop: "1px solid #F0ECE5", paddingTop: 12 }}>
        <button className="edu-btn-outline" style={{ padding: "5px 12px", fontSize: 12 }} onClick={handleCopy}>
          Copy
        </button>
        <button className="edu-btn-outline" style={{ padding: "5px 12px", fontSize: 12 }} onClick={handlePrint}>
          Print
        </button>
        {onRegenerate && (
          <button className="edu-btn-outline" style={{ padding: "5px 12px", fontSize: 12 }} onClick={onRegenerate} disabled={regenerating}>
            {regenerating ? "Regenerating…" : "Regenerate"}
          </button>
        )}
      </div>
    </div>
  );
}
